name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Step 3: Run Gradle tests
      - name: Run tests
        run: ./gradlew test

      # Step 4: Build the project
      - name: Build project
        run: ./gradlew build

      # Step 5: Extract version from Gradle
      - name: Get version from Gradle
        id: get_version
        run: |
          VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 6: Build Docker image with version tag
      - name: Build Docker image
        run: docker build -t githubactions:${{ env.VERSION }} .
